import axios, { type AxiosInstance } from 'axios';

/**
 * Infrastructure: HTTP client for the Spring Boot NexBell backend.
 *
 * Encapsulates all REST calls so application handlers stay decoupled
 * from transport details.
 */
export class NexBellHttpClient {
  private readonly http: AxiosInstance;

  constructor(baseURL: string) {
    this.http = axios.create({
      baseURL,
      timeout: 10_000,
      headers: { 'Content-Type': 'application/json' },
    });
  }

  /** POST /api/security/iot/presence — report HC-SR04 presence event */
  async reportPresence(): Promise<void> {
    await this.http.post('/api/security/iot/presence');
    console.log('[HTTP] Presence event reported to backend.');
  }

  /** POST /api/security/alarms/tampering — report tampering alarm event */
  async reportTampering(sensorType: 'MC38_MAGNETIC' | 'SW420_VIBRATION'): Promise<void> {
    await this.http.post('/api/security/alarms/tampering', { sensorType });
    console.log(`[HTTP] Tampering alarm reported to backend for sensor: ${sensorType}.`);
  }

  /**
   * POST /api/intercom/visit-requests/{id}/evidence
   * Attaches the pre-signed audio URL generated by AudioOrchestrationService.
   */
  async attachAudioEvidence(visitRequestId: number, audioUrl: string): Promise<void> {
    await this.http.post(`/api/intercom/visit-requests/${visitRequestId}/evidence`, {
      photoUrl: null,  // Camera omitted per spec
      audioUrl,
    });
    console.log(`[HTTP] Audio evidence attached for visitRequestId=${visitRequestId}`);
  }



  /**
   * POST /api/intercom/visit-requests/{id}/evidence
   * Attaches the photo URL captured by the OV2640 camera.
   */
  async attachPhotoEvidence(visitRequestId: number, photoUrl: string): Promise<void> {
    await this.http.post(`/api/intercom/visit-requests/${visitRequestId}/evidence`, {
      photoUrl,
      audioUrl: null,
    });
    console.log(`[HTTP] Photo evidence attached for visitRequestId=${visitRequestId}`);
  }


  /**
   * POST /api/intercom/visit-requests — create a new visit request triggered
   * by a doorbell press. Returns the created request ID.
   */
  async createVisitRequest(visitorName: string, apartmentId: number): Promise<number> {
    const res = await this.http.post('/api/intercom/visit-requests', {
      visitorName,
      apartmentId,
    });
    return (res.data as { id: number }).id;
  }

  /**
   * POST door unlock command forwarded from the backend via IoTHttpCommandGateway.
   * The edge service exposes this endpoint so the gateway can call it.
   * See EdgeCommandController.
   */
  async forwardUnlockCommand(visitRequestId?: number): Promise<void> {
    console.log('[HTTP] Unlock command forwarded from backend — publishing to MQTT.');
    // Actual MQTT publish is done by EdgeCommandController which receives this call.
  }
}
